# Root storage directory
# Required
storage: ./videos

# Global storage limit, will delete oldest videos from any monitor to stay below this
# Required
maxDiskGB: 10

monitors:
    # Monitor name, will also act as the ID
    # Should be unique
    # example:
        # Source of stream, should be something FFmpeg can read
        # Required
        # source: rtsp://username:password@example/stream

        # Max duration of video segments
        # Required
        # segmentDurationSeconds: 300

        # Max age of videos, anything older will be deleted
        # Set to 0 to disable check
        # maxAgeHours: 1

        # Storage limit for this monitor, oldest videos will be deleted to stay below this limit
        # Set to 0 to disable check
        # maxDiskGB: 5